### ISSUE TITLE
The Qt window creator in RenderManagerOpenGLQt5Example fails for 2 windows

### ISSUE THREAD

**Issue by russell-taylor** [sensics/OSVR-RenderManager#125]
When it creates two windows (due to using the mono display_mode in the server config file), the second window apparently never gets an expose event, so never draws.

The SDL-based default one (and the one in the RenderManagerOpenGLSharedContextExample) do display to both of the windows.

**Comment by steffen-kiess** [comment]
I don't think it is possible to use the same OpenGL context for different QGLWidgets in Qt. (See the answers to http://stackoverflow.com/questions/20955669/how-to-share-opengl-context-or-data). Doing so causes the data for both eyes to be drawn into the same QGLWidget.

What is possible is to tell Qt/OpenGL to share objects between two contexts. This shares things like VBOs etc. but not container objects (like VAOs or Framebuffers).

I've attached a patch [qt.diff](https://github.com/sensics/OSVR-RenderManager/files/339259/qt.diff) which will try to use different contexts which are sharing object; this requires making the proper context current for each display and creating Framebuffers per-display instead of globally (other objects, like Programs, can be shared across the contexts).

**Comment by russell-taylor** [comment]
Awesome!  Put this into a branch and made it work the the OpenGL interop case, and will pull-request to master.  Thanks!
