### ISSUE TITLE
Tutorials on enabling DirectMode for VRGate HMD?

### ISSUE THREAD

**Issue by ccll** [sensics/OSVR-RenderManager#133]
I've got the latest release of OSVR (v0.6-1197-g8796762), but could not find a way to enable DirectMode for VRGate HMD.
Here is my understanding of the process to support DirectMode:
1. Add vendor id (PNPID) to RenderManagerBase.cpp and wait for a binary release (DONE and MERGED, I suppose it should be contained in the g8796762 release)
2. Run EnableOSVRDirectMode.exe or EnableOSVRDirectModeAMD.exe to hide the registered display. Here is the output on my dev machine:
![image](https://cloud.githubusercontent.com/assets/5366582/16518281/95d674d4-3fb4-11e6-87ee-627774d1843f.png)
No VRGate in the list, is that means the VRGate PNPID is not included in this release?

Then I found [this troubleshooting](https://github.com/OSVR/OSVR-Docs/blob/master/Troubleshooting/RenderManager.md), and noticed there is a registry whitelist on NVIDIA cards to enable DirectMode for development, but unfortunately I couldn't find the CombinedWhitelist.reg file in anywhere from the installation directory of RenderManager 0.6.41.

I'm using NVIDIA GTX970 with driver 365.19,

**Comment by russell-taylor** [comment]
[whitelist_OSVR.zip](https://github.com/sensics/OSVR-RenderManager/files/344795/whitelist_OSVR.zip)

This is a file for the OSVR HDK from an older RenderManager installer.  You'll need to edit it to change SVR to the correct one for your HMD.  Know that nVidia has deprecated this whitelist feature and I don't know if it will still work on that version of the driver.  You will also need to reboot the machine after adding the entry.

**Comment by ccll** [comment]
Thanks for the solution, but unfortunately it's not working on this driver.
Is there anything else I can do?
A solution for both NVIDIA and AMD cards is better, cause we're cooperating with AMD and some of our contents will be running on AMD cards.

**Comment by russell-taylor** [comment]
Currently, the solutions are vendor-specific.  You'll need to contact nVidia to get them to add your device to their driver white-list.  Be aware that they have stopped DirectMode support for non-HDCP-compliant HMDs on laptops and on systems with multi GPUs (and they are warning that we should support it on any display going forward).

AMD has a different approach to getting devices registered, so you should contact them as well.

On the plus side, there is an API upgrade working its way through Microsoft that should provide a vendor-independent solution.  We're tracking it and plan to release a new driver when it comes out.  At that point, the entire rendering chain should be open source, because it will be using public APIs and not vendors-specific ones.  I don't have an ETA for this, other than it was supposed to have been out last August.

**Comment by russell-taylor** [comment]
In the meantime, you can add a frame of prediction to the client-side prediction interval and use the standard display mode.  Note that some displays have a frame less of latency when you drive them in portrait mode as opposed to landscape mode, so this may help as well.

**Comment by ccll** [comment]
It explains everything I need, thanks a lot!
I'll try the AMD approach first as we have LiquidVR available now.
