### ISSUE TITLE
D3D11 OpenDisplay returns uninitialized colorBuffer pointer

### ISSUE THREAD

**Issue by mdutton3** [sensics/OSVR-RenderManager#20]
The `RenderBufferD3D11` pointer (`openResults.buffers.D3D11`) looks to be valid but its contents are uninitialized. It's member pointers (e.g. `colorBuffer`) are neither NULL nor valid.

**Comment by russell-taylor** [comment]
This is fixed in the https://github.com/sensics/OSVR-RenderManager/tree/fixing-d3d-issues branch by removing these structures from the OpenDisplay() return structure.  They are not needed in the Present() path, and they are not needed until the callback handlers are called in the Render() path.

This will be pull-requested soon, so should be in the next release.
