### ISSUE TITLE
VRPN submodule fails to initialize for non-nda repo

### ISSUE THREAD

**Issue by adammunich** [sensics/OSVR-RenderManager#346]
I can't seem to initialize the VRPN submodule as instructed for non-NDA users. Is there something that has changed since the docs were last updated?

https://i.imgur.com/59GtdSk.png

**Comment by godbyk** [comment]
You wrote `git submodule init` before writing `git submodule init vendor/vrpn`, so git initialized all the submodules (including the NDA submodules) instead of just the VRPN submodule.

Try the following:

```bash
git submodule deinit --all
git submodule init vendor/vrpn
git submodule update
```

(I've never used `git submodule deinit`. If it doesn't work, then I'd probably just wipe out the OSVR-RenderManager directory and reclone the repository.)

**Comment by russell-taylor** [comment]
Updated the instructions to clarify and simplify and added a pull request.

**Comment by adammunich** [comment]
It seems you have to specify 

git submodule deinit --all
git submodule init vendor/vrpn
git submodule update vndor/vrpn`

Explicitly as to not throw an error. 

Now step two: move onto building it :-).

**Comment by adammunich** [comment]
It seems you have to specify `vendor/vrpn` explicitly as to not throw an error. As well, when you clone the repo, all NDA submodules are enabled and must be explicitly disabled.

`git submodule deinit --all`
`git submodule init vendor/vrpn`
`git submodule update vendor/vrpn`

Now step two: move onto building it :-).

**Comment by russell-taylor** [comment]
Excellent.  Be sure to have build OSVR-Core and its dependencies first.  You'll need to specify the locations of several libraries on Windows to get it to find all of the packages RenderManager needs to build.  On Linux, apt install will work.
