### ISSUE TITLE
jsonCPP

### ISSUE THREAD

**Issue by ChristophLGDV** [sensics/OSVR-RenderManager#35]
JsonCpp will not compile / generate out of the box using the latest CMake.

Using some external Jsoncpp with Cmake structure will complain about operator=() reference.

Some immediate directions would be highly appreciated.

**Comment by DuFF14** [comment]
There is a link to JsonCpp binaries from this page: http://wiki.osvr.com/doku.php?id=startingcore
I manually set the path to the JsonCpp cmake directory from the Cmake gui.

**Comment by ChristophLGDV** [comment]
Hello and thank you for this immediate reply.

By now I managed to bend a cmake project using the sources provided by > vrpn > jsoncpp
However that is hardly streamlined.
I also had to hardcode some other dependencies  (SDL I believe, and boost?).

It would be nice if there would be some immediate description in the repo, or if it would work out of the box.

(Background: I’m setting up a university VR course and have to install this in a pool. )

Best Regards
Christoph

**Comment by russell-taylor** [comment]
Can you tell which operating system you're having trouble with?  This may work out of the box on Ubuntu Linux with all of the packages installed normally, but it is not so clear how to make it work on Windows because it depends on where the rest of the libraries end up.  I'm guessing that "Point the CMake dependencies at the locations the libraries are installed" is not the kind of instruction that would be sufficiently helpful here.

**Comment by russell-taylor** [comment]
Also note that you can use a RenderManger binary installation on Windows, which will also have the benefit of being compiled against vendor-NDA codes for nVidia and AMD to enable DirectMode.

**Comment by ChristophLGDV** [comment]
Hello, Thank you or your reply.


I got it working by bending some dpendencies. A more streamlined json would be nice.

I already have the binary running.
Now I would like to implement my own mini sample.

The RenderManager repo seemed a good way to start.
Now it appears that I wont be able to use direct mode?

Is there an sdk along the lines of the oculus SDK?


Best Regards
Christoph

**Comment by russell-taylor** [comment]
Not knowing what operating system you are using, I can't answer your question about using DirectMode.  The project documentation at https://github.com/sensics/OSVR-RenderManager/blob/master/README.md describes this some more.

Basically, DirectMode is currently only implemented in Windows drivers for nVidia and AMD right now, so that is the only place anyone can use it.  When it becomes available for Linux and/or mac, we plan to implement it there as well.

You CAN use DirectMode on Windows by downloading and installing the installer from the developer download site at http://osvr.github.io/using/ which includes the required include, library, and DLL files to build and run your own apps using the RenderManager interface.  This is the same exact interface but has added functionality (it supports setting DirectMode to true in the config file).

You can also build the RenderManager yourself and get the same interface, but you won't have access to the vendor-NDA portions that implement DirectMode.

**Comment by ChristophLGDV** [comment]
Oh sorry.

I am using Win 10.

Another question, I notice some severe  smears when rendering the samples (and the ShadowRun Demo). I recon that low persistence is disabled. Can I enable it?

Or am I missing something else?


Best Regards

**Comment by russell-taylor** [comment]
You can use RenderManager/DirectMode on Windows 10 on recent nVidia and AMD cards with the latest drivers.  The installer includes the bin, lib, and include files needed to compile, link and run your own apps.  The source repository has the source for the example programs, which you can use to compile them as well.  You can compile from the source code and then just copy over the DLL from the installer presuming that you build from the source-code version that built the installed version (there is a git tag for each).

For persistence, I'm guessing you mean in the OSVR HDK.  That's something to take up on the hardware boards, where Yuval has been talking about this: https://gitter.im/OSVR/OSVR-General?at=56c63d0b5c3b0559674d3eeb

Let me know if we should keep this issue open, and if so what else is needed to get it resolved.

Thanks,
Russ

**Comment by VRguy** [comment]
Upgrade to latest OSVR HDK firmware using the tool from here:
http://osvr.github.io/using/

On Mon, Feb 29, 2016 at 2:56 PM, Russell Taylor <notifications@github.com>
wrote:

> You can use RenderManager/DirectMode on Windows 10 on recent nVidia and
> AMD cards with the latest drivers. The installer includes the bin, lib, and
> include files needed to compile, link and run your own apps. The source
> repository has the source for the example programs, which you can use to
> compile them as well. You can compile from the source code and then just
> copy over the DLL from the installer presuming that you build from the
> source-code version that built the installed version (there is a git tag
> for each).
>
> For persistence, I'm guessing you mean in the OSVR HDK. That's something
> to take up on the hardware boards, where Yuval has been talking about this:
> https://gitter.im/OSVR/OSVR-General?at=56c63d0b5c3b0559674d3eeb
>
> Let me know if we should keep this issue open, and if so what else is
> needed to get it resolved.
>
> Thanks,
> Russ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sensics/OSVR-RenderManager/issues/35#issuecomment-190355447>
> .
>



-- 
-- 
Yuval Boger
CEO | VRguy <http://www.vrguy.net>
Sensics, Inc. <http://www.sensics.com>

Latest news and blog posts:
21 Feb: VRguy podcast Episode 3: Paul Travers, CEO of Vuzix, on AR/VR in
the Enterprise and Consumer Markets
<http://sensics.com/vrguy-podcast-episode-3-paul-travers-ceo-of-vuzix-on-arvr-in-the-enterprise-and-consumer-markets/>
16 Feb: Vision Summit 2016: Using OSVR to Support (practically) Any Device
in AR/VR
<http://vrguy.blogspot.com/2016/02/vision-summit-2016-using-osvr-to.html>
25 Jan: Got new or custom HMD? Need direct render, time warping, distortion
correction and game engine integration?
<http://vrguy.blogspot.com/2016/01/got-new-hmd-need-direct-render-time.html>

**Comment by rpavlik** [comment]
(the jsoncpp sources you want are actually https://github.com/vrpn/jsoncpp/tree/0.y.z on Windows, with precompiled binaries at http://access.osvr.com/binary/deps/jsoncpp-0yz - they fix the bugs in the upstream jsoncpp)

**Comment by ChristophLGDV** [comment]
Thank you for your replies.

Since I got it working, got some more directions and finally found out that binary is better you may consider this closed.
Thank you.
