### ISSUE TITLE
Be able to specify three-letter display codes in config file for DirectMode

### ISSUE THREAD

**Issue by russell-taylor** [sensics/OSVR-RenderManager#54]
Be able to specify three-letter display codes in config file for DirectMode
		They should add new entries the same way that vendor does, but not look up the name.

**Comment by rpavlik** [comment]
Would prefer to have that just come with the display info in the descriptor, since that's not rendermanager-specific - so an HDK could say, hey, here's an array of possible hardware IDs that I might have:

```json
"hardwareIds": [
  [ "SEN", "1019"],
  [ "SVR", "1019"]
]
```

(Yes, I'd vote for including the product ID in string form as hex, and then parsing it with `std::stringstream` with a `std::hex` modifier - because nobody normally interacts with those in decimal. Some VR software uses the product id in decimal, but it's not pretty.)

**Comment by russell-taylor** [comment]
If we're going to parse as hex, the values should be "0x1019" to avoid confusing the person making the files.  Or they can be named with a name that has hex in it rather than just un-named string members.

We don't currently need the product ID for RenderManager's purposes, just the vendor ID.

Glad to have this issue moved to core if you prefer.

**Comment by rpavlik** [comment]
Sounds good to add the prefix. I think to avoid it getting unwieldly the tuple-style arrays are OK with the 0x in them.  We'll need product ID for core, and presumably at some point for more fine-grained direct mode controls.

Yes, I'd like this to be core.

**Comment by russell-taylor** [comment]
Handled in 74a20423cb3075034841b6cd12adbe1bee5919fe
