### ISSUE TITLE
RenderManager cmake build error

### ISSUE THREAD

**Issue by jacky-chuang** [sensics/OSVR-RenderManager#59]
When I try to build renderManager using cmake, it has the following error :+1: 
CMake Error at CMakeLists.txt:22 (find_package):
  Could not find a configuration file for package "osvr" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    D:/SW/OSVR-Core-Snapshot-v0.6-1169-ge9235a4-build252-vs12-64bit/OSVR-Core-Sn
apshot-v0.6-1169-ge9235a4-build252-vs12-64bit/lib/cmake/osvr/osvrConfig.cmake, v
ersion: 0.6 (64bit)

I download the osvr core 0.6.1169 from http://access.osvr.com/binary/osvr-core

**Comment by rpavlik** [comment]
Usually this is when you're trying to generate for Visual Studio 2013 (which implies 32-bit) and what you have is a 64-bit version of the deps (which is what you linked). You need to match the bitness of the dependency packages, or Visual Studio will give you really obscure errors later: that's why we set it up for CMake to give you these errors early.
