### ISSUE TITLE
core profile on linux (RenderManagerOpenGLCoreExample and others)

### ISSUE THREAD

**Issue by ChristophHaag** [sensics/OSVR-RenderManager#68]
I've seen a todo somewhere in the code about that but I don't find it right now. Anyway, it seems that it's hardcoded that only **APPLE** gets a core context:
https://github.com/sensics/OSVR-RenderManager/blob/db34892405935933437db309b23c22aa2e670509/osvr/RenderKit/RenderManagerOpenGL.cpp#L282-L287

That's especially bad for mesa because it supports anything above OpenGL 3.0 only with a core context.

Would there be any harm in using a core context on every platform?

**Comment by ChristophHaag** [comment]
With mesa I end up with GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT in this check in RenderManagerOpenGL::RenderEyeInitialize:
https://github.com/sensics/OSVR-RenderManager/blob/db34892405935933437db309b23c22aa2e670509/osvr/RenderKit/RenderManagerOpenGL.cpp#L555-L561
apitrace says `5218: message: api issue 4: FBO incomplete: depth attachment incomplete [-1]`

I don't know enough about OpenGL to trace this further, but the code is littered with `#ifdef __APPLE__`, so maybe there is a problem somewhere...

**Comment by russell-taylor** [comment]
Windows and Linux both support Compatibility contexts in OpenGL, which support both Legacy and Core.  Apple only supports Legacy and Core, not Compatibility, so the Legacy apps are not built on Apple (because they would not work).  The RenderManager OpenGL code path is currently compatible with OpenGLES 2.0 and with a Core profile; all of the Legacy code has been removed.

**Comment by russell-taylor** [comment]
The vast majority of the #ifdef __APPLE__ instances are to find the gl.h include file in the correct location (in OpenGL/gl.h rather than GL/gl.h where all other vendors place it).  The code compiles on Windows and Linux and Android, so I doubt that they are the cause.  Mesa has not to date been a development target for OSVR, but there hasn't been anything added that should preclude it from working.  I'm not familiar with which version of OpenGL it targets, so perhaps it does not support something that is supported by Windows, Linux, and OSX.  Glad to take a pull request to handle this in a way that is compatible with Mesa and with all of the existing interfaces.  In the meantime, I'll leave this issue open in case someone more familiar with Mesa porting knows an easy fix.

**Comment by ChristophHaag** [comment]
The compilation is not the problem: It compiles fine with mesa, but at runtime it errors out at the glsl 330 shaders, because the compatibility context defaults to 3.0, the latest version mesa supports the compatibility context with: https://cgit.freedesktop.org/mesa/mesa/tree/docs/GL3.txt#n25.

Simply removing the ifdef makes it use the OpenGL 3.3 core context, but when there are demo applications that require a 3.3 compatibility context, then I get why it can't unconditionally be set to a core context.

Since on linux there are both drivers that can use 3.3 with a compatibility and drivers that can only use 3.3 with a core context, maybe the `#ifdef __APPLE__` should be replaced with a runtime check of some sort. I guess that is something I can try making.

After sleeping a night about it I guess my second comment is probably a different problem.

**Comment by russell-taylor** [comment]
Did the insight while sleeping solve the problem?  If so, I'll go ahead and close the issue.  If not, can you share what still needs doing?  Thanks!

**Comment by ChristophHaag** [comment]
Well, the problem of this bug report is that on linux with mesa, render manager should use the OpenGL core profile. But it's hardcoded to only use a core profile on `__APPLE__`.

It would be nice if the application could request from the render manager to either create a core or a compatibility context. For example there's this render manager example application called `RenderManagerOpenGLCoreExample`. In the shaders it uses `#version 330 core`, but the OpenGL context that render manager creates is still a compatibility context, so it doesn't work on mesa...

I've looked a bit through the code and I'm not sure how to best do it, but this would be a possibility:
https://github.com/ChristophHaag/OSVR-RenderManager/commit/067405de29ce74bd58d2d3261fc6969d017c6234

(I'd like it the other way around better - OpenGL Core being the default and Compatibility being the special case that can be requested when really necessary, but I don't know if this breaks existing applications)

**Comment by russell-taylor** [comment]
I see where that is going.  If I understand things correctly, the Compatibility profile is a strict superset of Core, so that if it is available on an architecture then providing it is a more general solution that Core.

If that is correct, then it might be more appropriate to put in a compile-time check like is done for Apple to see if we're compiling with MesaGL and, if so, then to restrict the compiled applications to the Core one and ask for a Core context as is done on Apple for now.  This could be done as a compatibility #define, which asks for OpenGL_Core at library compile time and it could be turned on for both Apple and Mesa.

**Comment by ChristophHaag** [comment]
As far as I know, the only difference is that OpenGL Core removes some deprecated functionality like the Fixed Function Pipeline from OpenGL 3+, while OpenGL Compatibility still allows calling deprecated functions.

> to see if we're compiling with MesaGL and, if so, then to restrict the compiled applications

That works fine for single users, but when linux distributions want to make and distribute binary packages, they will have some users with the proprietary drivers and some users with mesa, so both would be kinda needed. That is, if there is really no way to get rid of the requirement for the compatibility profile altogether.

**Comment by russell-taylor** [comment]
I like the idea of providing multiple potential OpenGL contexts using different names in the create call.  We'll want APPLE to fail when you ask for a non-core context and to change the Core example application to ask for Core.  This is sort of shoe-horning two OpenGL contexts into one implementation, but I think that will be less confusing that putting out two basically-identical source codes with one for each.

By the way, I think that "get rid of the requirement for the compatibility profile altogether" means the same thing as "stop supporting applications using the Legacy profile".  Stated that way, it is not as appealing to me.

**Comment by ChristophHaag** [comment]
Well, APPLE and mesa on linux should fail. Currently on mesa it's printing `0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES` when trying to compile the distortion shader and I have no idea what happens on apple, probably something similar. On linux it has to be checked at runtime because users may run the same build of the program and render manager with different drivers.

And if it is changed this way, then all example programs need to be changed too. Right now the example programs work on APPLE, because the core profile is unconditionally used there. That's why it would be nice to have the core profile be the default..

**Comment by russell-taylor** [comment]
Right now, only the Core examples get compiled on the mac.  Most of the OpenGL apps fail when run on a mac (they are Legacy apps).  I'm okay with making the app specify OpenGLCore or OpenGLCompatibility and changing all of the apps to do that.

**Comment by ChristophHaag** [comment]
Ah, I found out what was wrong what I wrote my second comment for. I used sample-configs/renderManager.extended.landscape.json and got the incomplete framebuffer error there.

That may or may not an issue that needs to be addressed, but using sample-configs/osvr_server_config.renderManager.sample.json instead works much better - after setting direct rendering to false.

It still doesn't really work, because it says:
Mesa: User error: GL_INVALID_ENUM in glIsEnabled(GL_TEXTURE_2D)
Mesa: User error: GL_INVALID_ENUM in glEnable(GL_TEXTURE_2D)

As I don't know much about OpenGL programming, I googled that and it appears these are calls for the old pre-OpenGL3 fixed function pipeline that have been deprecated, so they do not work in a core profile.

Curious: If this is the case, why does it work on APPLE?

As far as mesa complains, these three lines are problematic:
https://github.com/sensics/OSVR-RenderManager/blob/07113abbd2099cd9827ff75dac2a087c6de3300c/osvr/RenderKit/RenderManagerOpenGL.cpp#L919
https://github.com/sensics/OSVR-RenderManager/blob/07113abbd2099cd9827ff75dac2a087c6de3300c/osvr/RenderKit/RenderManagerOpenGL.cpp#L922
https://github.com/sensics/OSVR-RenderManager/blob/07113abbd2099cd9827ff75dac2a087c6de3300c/osvr/RenderKit/RenderManagerOpenGL.cpp#L977

After commenting out these three lines, RenderManagerOpenGLCoreExample starts and displays this:
![osvrcore](https://cloud.githubusercontent.com/assets/781076/14827509/0c6bda7c-0be3-11e6-9cea-c2ba874dfe56.png)

(There seem to be a few more of these calls that just happened to not be hit)

All in all this seems to be nearly working on mesa.

**Comment by russell-taylor** [comment]
Sorry about that.  I've merged a pull request into master that removes these calls.  I verified that all of the test apps still work on Windows without them.  Thanks for helping to chase this down!

No idea how that worked on Apple.  Either it got added in since I checked on Apple or else that must be defined somewhere in the header files I was using.

**Comment by russell-taylor** [comment]
Closing this issue.  Go ahead and re-open if it is still not working for you.

**Comment by ChristophHaag** [comment]
Well, so far the rendering is working, but still only really when either changing the code to use a core profile or pretending to support the 3.3 compatibility profile by setting the environment variables `MESA_GL_VERSION_OVERRIDE=3.3 MESA_GLSL_VERSION_OVERRIDE=330`.

**Comment by ChristophHaag** [comment]
I'll go ahead and close this issue. Intel and radeonsi have been supporting OpenGL 4.6 with the compatibility profile for a while now.

It would still be nice to have render manager and all samples use only core GL, but at least it's not crucial for functionality on mesa anymore.
